In [ ]:
print('anything')

anything


In [ ]:
import numpy as np

In [ ]:
numbers = np.array([1,2,3,4])

In [ ]:
numbers

array([1, 2, 3, 4])

Dimensions

In [ ]:
arr_0 = np.array(3)

In [ ]:
arr_0

array(3)

In [ ]:
print(type(arr_0))

<class 'numpy.ndarray'>


In [ ]:
arr_0.ndim

0

In [ ]:
arr_1 = np.array([1])

In [ ]:
print(type(arr_1))

<class 'numpy.ndarray'>


In [ ]:
arr_1.ndim

1

In [ ]:
arr_11 = np.array([1,2,3,4,5,6,7])

In [ ]:
print(type(arr_11))

<class 'numpy.ndarray'>


In [ ]:
arr_11.ndim

1

In [ ]:
arr_2 = np.array([[1.4,5,6]])

In [ ]:
arr_2.ndim

2

In [ ]:
arr_3 = np.array([[[1,3,4,5,6,7]]])

In [ ]:
arr_3.ndim

3

Array Attributes

In [ ]:
integers = np.array([[1,2,3,4],[6,7,8,9]])

In [ ]:
integers.ndim

2

In [ ]:
integers.dtype

dtype('int64')

In [ ]:
floats = np.array([[1.2,1.3,6.6],[1.3,7.5,9.0]])

In [ ]:
floats.dtype

dtype('float64')

In [ ]:
sting = np.array(['cat','dog','cow'])

In [ ]:
sting

array(['cat', 'dog', 'cow'], dtype='<U3')

In [ ]:
integers

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
integers.shape

(2, 4)

In [ ]:
a = integers.reshape(4,2)

In [ ]:
a.shape

(4, 2)

In [ ]:
integers.size

8

Array Operstors

In [ ]:
array_new = np.arange(1,11)

In [ ]:
array_new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
array_new+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
array_new*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
array_new+array_new

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
array_new/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
array_new>10

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
array_new>=10

array([False, False, False, False, False, False, False, False, False,
        True])

Numpy Function

In [ ]:
grades = np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])

In [ ]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [ ]:
grades.shape

(4, 3)

In [ ]:
grades.ndim

2

In [ ]:
grades.max()

100

In [ ]:
grades.min()

70

In [ ]:
grades.sum()

1054

In [ ]:
grades.std()

8.792357792739987

In [ ]:
grades.mean()

87.83333333333333

In [ ]:
grades.var()

77.30555555555556

Indedxing and Selection

In [ ]:
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
print(array_2d.ndim)
print(array_2d.shape)

2
(3, 3)


In [ ]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
array_2d[1,]

array([20, 25, 30])

In [ ]:
array_2d[1,][0]

20

In [ ]:
array_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [ ]:
array_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])